DROP DATABASE IF EXISTS `RESTAURANT`;
create DATABASE RESTAURANT;
use RESTAURANT;

DROP TABLE IF EXISTS `EMPLOYEES`;
DROP TABLE IF EXISTS `EMPLOYEE_DEPENDENTS`;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS `MENU`;
DROP TABLE IF EXISTS `ORDER_ITEM`;
DROP TABLE IF EXISTS `CHEF`;
DROP TABLE IF EXISTS `PAYMENT`;
DROP TABLE IF EXISTS `TABLE`;
DROP TABLE IF EXISTS `IS_SERVING`;
DROP TABLE IF EXISTS `WAITER`;
DROP TABLE IF EXISTS `FOOD IDS`;
DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE `EMPLOYEES`(
	EMPLOYEE_ID BIGINT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	CONTACT_NUMBER BIGINT NOT NULL,
	SALARY BIGINT NOT NULL,
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `EMPLOYEE_DEPENDENTS`(
	EMPLOYEE_ID BIGINT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	FOREIGN KEY(`EMPLOYEE_ID`) REFERENCES `EMPLOYEES`(`EMPLOYEE_ID`)	
);

CREATE TABLE `TABLE`(
	TABLE_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT,
	ORDER_ID BIGINT,
	PRIMARY KEY(`TABLE_ID`)
);

CREATE TABLE `CUSTOMER`(
	CUSTOMER_ID BIGINT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	PAYMENT_ID BIGINT,
	ORDER_ID BIGINT,
	TABLE_ID BIGINT NOT NULL,
	PRIMARY KEY(`CUSTOMER_ID`)
);

CREATE TABLE `ORDER`(
	ORDER_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	PAYMENT_ID BIGINT NOT NULL,
	PRIMARY KEY(`ORDER_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`)
);

CREATE TABLE `PAYMENT`(
	PAYMENT_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	AMOUNT BIGINT NOT NULL,
	PAYMENT_TYPE VARCHAR(30),
	PAYMENT_DATE DATE,
	STATUS VARCHAR(30) NOT NULL,
	PRIMARY KEY(`PAYMENT_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`)
);

CREATE TABLE `MENU`(
	FOOD_ID BIGINT NOT NULL,
	FOOD_ITEM VARCHAR(30) NOT NULL,
	PRICE BIGINT NOT NULL,
	PRIMARY KEY(`FOOD_ID`)
);

CREATE TABLE `CHEF`(
	EMPLOYEE_ID BIGINT NOT NULL,
	ORDER_ID BIGINT,
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `ORDER_ITEM`(
	ORDER_ID BIGINT NOT NULL,
	FOOD_ID BIGINT NOT NULL,
	QUANTITY BIGINT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	UNIT_PRICE BIGINT NOT NULL,
	CHEF_ID BIGINT NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	FOREIGN KEY(`FOOD_ID`) REFERENCES `MENU`(`FOOD_ID`),
	FOREIGN KEY(`CHEF_ID`) REFERENCES `CHEF`(`EMPLOYEE_ID`)
);

CREATE TABLE `WAITER`(
	EMPLOYEE_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT,
	ORDER_ID BIGINT,
	TABLE_ID BIGINT,	
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `IS_SERVING`(
	EMPLOYEE_ID BIGINT NOT NULL,
	TABLE_ID BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	FOREIGN KEY(`EMPLOYEE_ID`) REFERENCES `WAITER`(`EMPLOYEE_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
	FOREIGN KEY(`TABLE_ID`) REFERENCES `TABLE`(`TABLE_ID`)
);

CREATE TABLE `FOOD_IDS`(
	FOOD_ID BIGINT NOT NULL,
	ORDER_ID BIGINT NOT NULL,
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	PRIMARY KEY(`FOOD_ID`,`ORDER_ID`)
);

INSERT INTO `TABLE` VALUES (1, NULL, NULL);
INSERT INTO `TABLE` VALUES (2, NULL, NULL);
INSERT INTO `TABLE` VALUES (3, NULL, NULL);
INSERT INTO `TABLE` VALUES (4, NULL, NULL);
INSERT INTO `TABLE` VALUES (5, NULL, NULL);
INSERT INTO `TABLE` VALUES (6, NULL, NULL);
INSERT INTO `TABLE` VALUES (7, NULL, NULL);
INSERT INTO `TABLE` VALUES (8, NULL, NULL);

INSERT INTO `MENU` VALUES (1, 'PIZZA', 300);
INSERT INTO `MENU` VALUES (2, 'WHITE_SAUCE_PASTA', 200);
INSERT INTO `MENU` VALUES (3, 'VEG_BURGER', 100);
INSERT INTO `MENU` VALUES (4, 'CHICKEN_BURGER', 150);
INSERT INTO `MENU` VALUES (5, 'VEG_SOUP', 150);
INSERT INTO `MENU` VALUES (6, 'PANEER_TIKKA', 300);
INSERT INTO `MENU` VALUES (7, 'RED_SAUCE_PASTA', 250);
INSERT INTO `MENU` VALUES (8, 'VEG_COMBO', 400);
INSERT INTO `MENU` VALUES (9, 'PASTA_MEAL', 300);
INSERT INTO `MENU` VALUES (10, 'BURGER_MEAL', 300);


INSERT INTO `EMPLOYEES` VALUES (1, 'JOHN', 'DOE', 9878984323, 10000);
INSERT INTO `EMPLOYEES` VALUES (2, 'JOHNNY', '', 9871114323, 20000);
INSERT INTO `EMPLOYEES` VALUES (3, 'MAXY', 'HUTT', 9872224323, 10000);
INSERT INTO `EMPLOYEES` VALUES (4, 'HIGH', 'FIVE', 9878984323, 20000);
INSERT INTO `EMPLOYEES` VALUES (5, 'DAVE', 'DAS', 9878981111, 20000);
INSERT INTO `EMPLOYEES` VALUES (6, 'JOE', 'WYATT', 9878989003, 20000);
INSERT INTO `EMPLOYEES` VALUES (7, 'RAJ', 'KOO', 9989984323, 10000);
INSERT INTO `EMPLOYEES` VALUES (8, 'JOEY', 'TRIB', 9878121223, 20000);
INSERT INTO `EMPLOYEES` VALUES (9, 'BRAD', 'DOE', 9878984323, 10000);
INSERT INTO `EMPLOYEES` VALUES (10, 'JOHN', 'WICK', 9999984323, 10000);

INSERT INTO `CHEF` VALUES (2, NULL);
INSERT INTO `CHEF` VALUES (4, NULL);
INSERT INTO `CHEF` VALUES (5, NULL);
INSERT INTO `CHEF` VALUES (6, NULL);
INSERT INTO `CHEF` VALUES (8, NULL);

INSERT INTO `WAITER` VALUES (1, NULL, NULL, NULL);
INSERT INTO `WAITER` VALUES (3, NULL, NULL, NULL);
INSERT INTO `WAITER` VALUES (7, NULL, NULL, NULL);
INSERT INTO `WAITER` VALUES (9, NULL, NULL, NULL);
INSERT INTO `WAITER` VALUES (10, NULL, NULL, NULL);